name: CD Pipeline

on:
  workflow_run:
    workflow: ["CI Pipeline"]
    types:
      - completed

  jobs:
    deploy:
      name: Deploy frontend to vercel
      runs-on: ubuntu-latest
      if: ${{github.event.workflows_runs.conclusion=='success'}} 

      steps:
        - name: Trigger vercel deployment
          runs: | 
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
