name: CD Pipeline

on:
  workflow_run:
    workflow: ["CI Pipeline"]
    types:
      - completed

  jobs:
    deploy-frontend:
      name: Deploy frontend to vercel
      runs-on: ubuntu-latest
      if: ${{github.event.workflows_runs.conclusion=='success'}} 

      steps:
        - name: Trigger vercel deployment
          runs: | 
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"

    deploy-baclend:
      name: Deploy backend on render
      runs-on: ubuntu-latest
      if: ${{github.event.workflow_run.conclusion='success'}}   

      steps:
        - name: Trigger render deployment
          runs: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
    


