name: CI Pipeline

on:
  push:
    branches: [main]
  pull:
    branches: [main]

jobs:
  frontend: Frontend - Next.js Application
  runs-on: ubuntu-lastest
  defaults:
    runs:
      working-directory: frontend
    
  steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Install dependencies
      run: npm install

    - name: List
      run: npm run list --if-present
    
    - name: Build Next.js app
      run: npm run build

  backend:
    name: Backend - Express Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test --if-present